### ISSUE TITLE
make release error

### ISSUE THREAD

**Issue by MrLittleWhite** [crystal-china/translater#2]
shards install --without-development
Resolving dependencies
Fetching https://github.com/crystal-lang/crystal-sqlite3.git
Fetching https://github.com/zw963/selenium.cr.git
Fetching https://github.com/wyhaines/timeout.cr.git
Fetching https://github.com/crystal-lang/crystal-db.git
Using selenium (0.12.1 at 0562b99)
Using db (0.13.1)
Using sqlite3 (0.21.0)
Using timeout (0.1.0 at 130d889)
crystal build --no-debug --link-flags=-s --release --progress -Dstrict_multi_assign -Dno_number_autocast -Duse_pcre2 -Dpreview_overload_order  -o bin/translater
Usage: crystal build [options] [programfile] [--] [arguments]

Options:
    --cross-compile                  cross-compile
    -d, --debug                      Add full symbolic debug info
    --no-debug                       Skip any symbolic debug info
    --frame-pointers auto|always|non-leaf
                                     Control the preservation of frame pointers
    -D FLAG, --define FLAG           Define a compile-time flag
    --emit [asm|obj|llvm-bc|llvm-ir] Comma separated list of types of output for the compiler to emit
    -f text|json, --format text|json Output format: text (default), json
    --error-trace                    Show full error trace
    -h, --help                       Show this message
    --ll                             Dump ll to Crystal's cache directory
    --link-flags FLAGS               Additional flags to pass to the linker
    --mcpu CPU                       Target specific cpu type
    --mattr CPU                      Target specific features
    --mcmodel MODEL                  Target specific code model
    --warnings all|none              Which warnings to detect. (default: all)
    --error-on-warnings              Treat warnings as errors.
    --exclude-warnings <path>        Exclude warnings from path (default: lib)
    --no-color                       Disable colored output
    --no-codegen                     Don't do code generation
    -o                               Output filename
    --prelude                        Use given file as prelude
    --release                        Compile in release mode (-O3 --single-module)
    -O LEVEL                         Optimization mode: 0 (default), 1, 2, 3, s, z
    -s, --stats                      Enable statistics output
    -p, --progress                   Enable progress output
    -t, --time                       Enable execution time output
    --single-module                  Generate a single LLVM module
    --threads NUM                    Maximum number of threads to use
    --target TRIPLE                  Target triple
    --verbose                        Display executed commands
    --static                         Link statically
    --stdin-filename                 Source file name to be read from STDIN
make: *** [release] Error 1

**Comment by zw963** [comment]
timeout shard not work on latest Crystal, can you download the binary directly from release page?

I create a issue there, if upstream fixed, then build without error.

**Comment by zw963** [comment]
timeout shards fixed, it can built on 1.14.0 now.
